# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: e1c6c4ebd8c5854fdfe2b54248575bf97bf3eca1dbc6ff646491488290367665af4db881d7d757cae9617030ced45a4667e0a41631c4213496d83efc19a6142c

test:
  secret_key_base: 7ca2b76b7d6a32ed7089b9fb23303fb0a538cb738ade233b5dd1d5de6b3fffb4ebc632163e222ad164a1de813ba32b9d2c0eedfb0f152bcddf4ea793a65a9a22

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
